// Embedded RSVP guest list and table-seating assignments, generated from
// the couple's RSVP export, seating spreadsheet, and welcome-event RSVPs.
// Loaded via buttons on the Guests and Seating tabs - see dataloader.js.
// Regenerate this file (don't hand-edit) if the source spreadsheets change.
window.PRESET_GUESTS = [
  {
    "name": "Rosenda Aguilar",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Salvador Garcia",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Ana Emilia Garcia Aguilar",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Gina Avilez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Nacho Vazquez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Sofi Vazquez Avilez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Patricio Vazquez Avilez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Javier Ballesteros",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Lily Barreras",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Dario Ballesteros Dalessio",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Sebastian Ballesteros Dalessio",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Melanie Barnaba",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex college friends (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 3",
    "notes": "Seating note: Alex college friends (English)"
  },
  {
    "name": "Dany Stueland",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex college friends (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 3",
    "notes": "Seating note: Alex college friends (English)"
  },
  {
    "name": "Lety Barrera",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Tere Barrera",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Ash Bell",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Lucas Bonnet",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Guest of Lucas Bonnet",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Ceremony: Declined, Reception: Attending; Unnamed plus-one from RSVP form"
  },
  {
    "name": "Meredith Bourne",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Mark Fetzko",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Alex Bourne",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Anna Bourne",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Rashke Bradley",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex friends / gay table",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 6",
    "notes": "Seating note: Alex friends / gay table"
  },
  {
    "name": "Kayla Shames",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Jesus Mondragon",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Alaina Kuehr",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Joe Cummins",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Guest of Joe Cummins",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Amy Currie",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Philip Danziger",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Fancy peeps (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 10",
    "notes": "Seating note: Fancy peeps (English); Botanical Garden Stroll: Maybe (2); Munch & Mingle: Yes"
  },
  {
    "name": "Shannon Firooz",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Fancy peeps (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 10",
    "notes": "Seating note: Fancy peeps (English)"
  },
  {
    "name": "Tori Darnell",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Jake friends (Work/Ithaca)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 5",
    "notes": "Seating note: Jake friends (Work/Ithaca)"
  },
  {
    "name": "Cory Tripathy",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Jake friends (Work/Ithaca)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 5",
    "notes": "Seating note: Jake friends (Work/Ithaca)"
  },
  {
    "name": "Andrew Davis",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex friends / gay table",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 6",
    "notes": "Seating note: Alex friends / gay table"
  },
  {
    "name": "Abigail Swanson",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Dr. Michael Delage Jr.",
    "email": "",
    "phone": "",
    "side": "",
    "group": "DnD",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 4",
    "notes": "Seating note: DnD; Botanical Garden Stroll: Maybe (1); Munch & Mingle: Yes; Ann Arbor help: I can help with set-up and/or clean-up!"
  },
  {
    "name": "Guest of Michael Delage",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Krista Drislane",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Cameron Dunbar",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex friends / gay table",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 6",
    "notes": "Seating note: Alex friends / gay table; Botanical Garden Stroll: Yes (2); Munch & Mingle: Yes"
  },
  {
    "name": "Lauren Claire Ebbage",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Vanessa Eisenhower",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Miriam Epstein",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Ma. Elena Escalona Gonz\u00e1lez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Gerardo Gordillo",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Elias Diaz Escalona",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex family (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 7",
    "notes": "Seating note: Alex family (Spanish)"
  },
  {
    "name": "Darlene Ferrer",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Kevin Chen",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Chloe Frey",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex friends / gay table",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 6",
    "notes": "Seating note: Alex friends / gay table; Botanical Garden Stroll: Yes (3); Munch & Mingle: Yes; Ann Arbor help: I can provide a dish!"
  },
  {
    "name": "Colby Chase",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex friends / gay table",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 6",
    "notes": "Seating note: Alex friends / gay table"
  },
  {
    "name": "Katherine Jones",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex friends / gay table",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 6",
    "notes": "Seating note: Alex friends / gay table"
  },
  {
    "name": "Natalie Garnett",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Botanical Garden Stroll: Yes; Munch & Mingle: Maybe; Ann Arbor help: I can help with set-up and/or clean-up!"
  },
  {
    "name": "Veronica Gilwan",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med school (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 8",
    "notes": "Seating note: Alex Med school (English); Botanical Garden Stroll: Maybe; Munch & Mingle: Maybe; Ann Arbor help: I can provide a dish!; Comment: Im having surgery August 23 rd but i would love to come"
  },
  {
    "name": "David Gilwan",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med school (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 8",
    "notes": "Seating note: Alex Med school (English)"
  },
  {
    "name": "Petra Glenn",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Aurora Gonzalez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex high school friends (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 2",
    "notes": "Seating note: Alex high school friends (Spanish); Botanical Garden Stroll: Yes (2); Munch & Mingle: Yes; Ann Arbor help: I can help with set-up and/or clean-up!"
  },
  {
    "name": "Darryl Zuckerman",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex high school friends (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 2",
    "notes": "Seating note: Alex high school friends (Spanish)"
  },
  {
    "name": "Silvia Gonzalez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Jose Luis Cortes Gallegos",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Ms. Rosa Gonzalez Lopezlira",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Main table with us!",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 1",
    "notes": "Seating note: Main table with us!; Botanical Garden Stroll: Yes (Four); Munch & Mingle: Yes; Ann Arbor help: I can help with set-up and/or clean-up!"
  },
  {
    "name": "Mr. Laurent Loinard",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Main table with us!",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 1",
    "notes": "Seating note: Main table with us!"
  },
  {
    "name": "Lucy Gonz\u00e1lez Le\u00f3n",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex family (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 7",
    "notes": "Seating note: Alex family (Spanish)"
  },
  {
    "name": "Ms. Mar\u00eda Josefa Gonz\u00e1lez Marina",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex family (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 7",
    "notes": "Seating note: Alex family (Spanish)"
  },
  {
    "name": "Ricardo Garc\u00eda Berumen Segura",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex family (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 7",
    "notes": "Seating note: Alex family (Spanish)"
  },
  {
    "name": "George Gull",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Main table with us!",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 1",
    "notes": "Seating note: Main table with us!"
  },
  {
    "name": "Nancy Potter",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Main table with us!",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 1",
    "notes": "Seating note: Main table with us!"
  },
  {
    "name": "Jeremiah Harmon",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Youngins /M -dining (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 11",
    "notes": "Seating note: Youngins /M -dining (English); Botanical Garden Stroll: Yes; Munch & Mingle: No; Ann Arbor help: I can help with set-up and/or clean-up!"
  },
  {
    "name": "Ela Pananon",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Youngins /M -dining (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 11",
    "notes": "Seating note: Youngins /M -dining (English)"
  },
  {
    "name": "Lorraine Heinrichs",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Alex Herter",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Ceremony: Declined, Reception: Attending"
  },
  {
    "name": "Guest of Alex Herter",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Ceremony: Declined, Reception: Attending; Unnamed plus-one from RSVP form"
  },
  {
    "name": "Karin Hollenberg Haddad",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Demian Garnica",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Camila Garnica Hollenberg",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Sebastian Garnica Hollenberg",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Carlie Hovland",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Austin Hovland",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Alexander Kaminsky",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Tara Kaminsky",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Erica Kanzinger",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Jake friends (Work/Ithaca)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 5",
    "notes": "Seating note: Jake friends (Work/Ithaca)"
  },
  {
    "name": "Dave Perczak",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Jake friends (Work/Ithaca)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 5",
    "notes": "Seating note: Jake friends (Work/Ithaca); Botanical Garden Stroll: No; Munch & Mingle: No; Comment: we\u2019ll be arriving late on Saturday to our hotel. We\u2019ll text if we arrive early but I don\u2019t think we\u2019ll be able to make it."
  },
  {
    "name": "Soha Kazmi",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med school (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 8",
    "notes": "Seating note: Alex Med school (English)"
  },
  {
    "name": "Mohan Kolla",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med school (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 8",
    "notes": "Seating note: Alex Med school (English)"
  },
  {
    "name": "Della Keahna Warrior",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Fancy peeps (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 10",
    "notes": "Seating note: Fancy peeps (English)"
  },
  {
    "name": "Grant",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Fancy peeps (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 10",
    "notes": "Seating note: Fancy peeps (English)"
  },
  {
    "name": "Francis Keahna Warrior",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Botanical Garden Stroll: Maybe (three); Munch & Mingle: Yes; Comment: we get in around 2pm!"
  },
  {
    "name": "Jack Ramey",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Fancy peeps (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 10",
    "notes": "Seating note: Fancy peeps (English)"
  },
  {
    "name": "Samuel Lehn",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med School (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 9",
    "notes": "Seating note: Alex Med School (English)"
  },
  {
    "name": "Erin Nichols",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med School (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 9",
    "notes": "Seating note: Alex Med School (English)"
  },
  {
    "name": "Johanna Li",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Main table with us!",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 1",
    "notes": "Seating note: Main table with us!"
  },
  {
    "name": "Susan Lin",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Fancy peeps (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 10",
    "notes": "Seating note: Fancy peeps (English); Botanical Garden Stroll: Maybe (2); Munch & Mingle: Yes; Comment: If the gardens walk is a drop-by whenever during the time frame sort of event then I may be able attend with my partner. But if it's a structured event then we will definitely commit to the evening Munch and Mingle!"
  },
  {
    "name": "Jonah",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Fancy peeps (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 10",
    "notes": "Seating note: Fancy peeps (English)"
  },
  {
    "name": "Valencia Little-Paz",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "John Little-Paz",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Guillaume Loinard-Gonzalez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex college friends (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 3",
    "notes": "Seating note: Alex college friends (English)"
  },
  {
    "name": "Lei Rivas Moron",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex college friends (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 3",
    "notes": "Seating note: Alex college friends (English)"
  },
  {
    "name": "Alex Loinard-Gonz\u00e1lez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Jake Seegers",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Kitty Lopezlira",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex family (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 7",
    "notes": "Seating note: Alex family (Spanish)"
  },
  {
    "name": "Nuria Castells",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex family (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 7",
    "notes": "Seating note: Alex family (Spanish)"
  },
  {
    "name": "Gina (Patricia Eugenia) Lopezlira",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex family (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 7",
    "notes": "Seating note: Alex family (Spanish)"
  },
  {
    "name": "Raul Lopezlira",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Brian Mastenbrook",
    "email": "",
    "phone": "",
    "side": "",
    "group": "DnD",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 4",
    "notes": "Seating note: DnD"
  },
  {
    "name": "Ms. Mira Menon",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Guest of Mira Menon",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Lupita Mier Silva",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex college friends (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 3",
    "notes": "Seating note: Alex college friends (English)"
  },
  {
    "name": "Arguro Gil Jacome",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex college friends (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 3",
    "notes": "Seating note: Alex college friends (English)"
  },
  {
    "name": "Mr. Paul Mikowski",
    "email": "",
    "phone": "",
    "side": "",
    "group": "DnD",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 4",
    "notes": "Seating note: DnD"
  },
  {
    "name": "Mrs. Alex Mikowski",
    "email": "",
    "phone": "",
    "side": "",
    "group": "DnD",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 4",
    "notes": "Seating note: DnD"
  },
  {
    "name": "Lourdes Moron",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Carlos Rivera",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Ryan Narvaez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Lisa Noselli",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Unnamed guest 1 of 4 (RSVP export, near Lisa Noselli)",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Unnamed guest 2 of 4 (RSVP export, near Lisa Noselli)",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Unnamed guest 3 of 4 (RSVP export, near Lisa Noselli)",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Unnamed guest 4 of 4 (RSVP export, near Lisa Noselli)",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Olivia Oligny-Leggett",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Michael Vecellio",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Angie Perez",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Youngins /M -dining (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 11",
    "notes": "Seating note: Youngins /M -dining (English); Botanical Garden Stroll: Yes (-); Munch & Mingle: Maybe; Ann Arbor help: I can provide a dish!; Comment: None!"
  },
  {
    "name": "Andre daCosta",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Albert Pertel",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Aja Sharma",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Rae Powers",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex friends / gay table",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 6",
    "notes": "Seating note: Alex friends / gay table"
  },
  {
    "name": "Geeta Rastogi",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med school (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 8",
    "notes": "Seating note: Alex Med school (English); Botanical Garden Stroll: No (2); Munch & Mingle: Yes"
  },
  {
    "name": "Nishant Mishra",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med school (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 8",
    "notes": "Seating note: Alex Med school (English)"
  },
  {
    "name": "David Ristedt",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex high school friends (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 2",
    "notes": "Seating note: Alex high school friends (Spanish)"
  },
  {
    "name": "Kelly Ristedt",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex high school friends (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 2",
    "notes": "Seating note: Alex high school friends (Spanish)"
  },
  {
    "name": "Kris Romer",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Madeleine Russell",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med School (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 9",
    "notes": "Seating note: Alex Med School (English)"
  },
  {
    "name": "Ben Laubach",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med School (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 9",
    "notes": "Seating note: Alex Med School (English)"
  },
  {
    "name": "Maisey Schuler",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med School (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 9",
    "notes": "Seating note: Alex Med School (English); Botanical Garden Stroll: No; Munch & Mingle: No"
  },
  {
    "name": "Kyle Franson",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med School (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 9",
    "notes": "Seating note: Alex Med School (English)"
  },
  {
    "name": "Douglas Seegers",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Guest of Douglas Seegers",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Kerri Slack",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Invited",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Jasmine Stanton",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Carrie Stock",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Mr. Silas Talley",
    "email": "",
    "phone": "",
    "side": "",
    "group": "DnD",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 4",
    "notes": "Seating note: DnD; Botanical Garden Stroll: Yes (2); Munch & Mingle: Yes; Ann Arbor help: I can provide a dish!"
  },
  {
    "name": "Mrs. Jess Talley",
    "email": "",
    "phone": "",
    "side": "",
    "group": "DnD",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 4",
    "notes": "Seating note: DnD"
  },
  {
    "name": "Timothy Vanhala",
    "email": "",
    "phone": "",
    "side": "",
    "group": "DnD",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 4",
    "notes": "Welcome Dinner RSVP: Attending; Seating note: DnD"
  },
  {
    "name": "Jacalyn Wasserman",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Ashley Wilson",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Youngins /M -dining (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 11",
    "notes": "Seating note: Youngins /M -dining (English); Botanical Garden Stroll: No; Munch & Mingle: No"
  },
  {
    "name": "Chloe Tyler",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Youngins /M -dining (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 11",
    "notes": "Seating note: Youngins /M -dining (English)"
  },
  {
    "name": "Emily Wollan",
    "email": "",
    "phone": "",
    "side": "",
    "group": "DnD",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 4",
    "notes": "Seating note: DnD; Botanical Garden Stroll: No; Munch & Mingle: No"
  },
  {
    "name": "Guest of Emily Wollan",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Vanessa Wood",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Botanical Garden Stroll: Yes (Me- maybe Lucas); Munch & Mingle: Yes; Comment: May arrive late to first one because arriving the 3rd- thanks!"
  },
  {
    "name": "Guest of Vanessa Wood",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": "Unnamed plus-one from RSVP form"
  },
  {
    "name": "Rachel Zhang",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med School (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 9",
    "notes": "Seating note: Alex Med School (English)"
  },
  {
    "name": "Lexi Howard",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex Med School (English)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 9",
    "notes": "Seating note: Alex Med School (English); Botanical Garden Stroll: No (2); Munch & Mingle: Yes; Comment: We aren\u2019t planning to attend the botanical gardens, but definitely let us know if you need help setting up/tearing down!"
  },
  {
    "name": "Aaron Zuckerman",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Sarah Zuckerman?",
    "email": "",
    "phone": "",
    "side": "",
    "group": "",
    "status": "Declined",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "",
    "notes": ""
  },
  {
    "name": "Hannah Zuckerman",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex high school friends (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 2",
    "notes": "Seating note: Alex high school friends (Spanish); Botanical Garden Stroll: Yes (1); Munch & Mingle: Yes"
  },
  {
    "name": "Sam Zuckerman",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex high school friends (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 2",
    "notes": "Seating note: Alex high school friends (Spanish)"
  },
  {
    "name": "Arcadia Lee",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex high school friends (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 2",
    "notes": "Seating note: Alex high school friends (Spanish)"
  },
  {
    "name": "Zach Zuckerman",
    "email": "",
    "phone": "",
    "side": "",
    "group": "Alex high school friends (Spanish)",
    "status": "Accepted",
    "meal": "",
    "partySize": 1,
    "plusOne": "",
    "inviteSent": "",
    "inviteMethod": "",
    "reminder": "No",
    "tags": "Table 2",
    "notes": "Seating note: Alex high school friends (Spanish)"
  }
];

window.PRESET_SEATING = [
  {
    "table": "1",
    "guest": "Alex"
  },
  {
    "table": "1",
    "guest": "Jake"
  },
  {
    "table": "1",
    "guest": "George Gull"
  },
  {
    "table": "1",
    "guest": "Johanna Li"
  },
  {
    "table": "1",
    "guest": "Mr. Laurent Loinard"
  },
  {
    "table": "1",
    "guest": "Ms. Rosa Gonzalez Lopezlira"
  },
  {
    "table": "1",
    "guest": "Nancy Potter"
  },
  {
    "table": "2",
    "guest": "Arcadia Lee"
  },
  {
    "table": "2",
    "guest": "Aurora Gonzalez"
  },
  {
    "table": "2",
    "guest": "Darryl Zuckerman"
  },
  {
    "table": "2",
    "guest": "David Ristedt"
  },
  {
    "table": "2",
    "guest": "Hannah Zuckerman"
  },
  {
    "table": "2",
    "guest": "Kelly Ristedt"
  },
  {
    "table": "2",
    "guest": "Sam Zuckerman"
  },
  {
    "table": "2",
    "guest": "Zach Zuckerman"
  },
  {
    "table": "3",
    "guest": "Arguro Gil Jacome"
  },
  {
    "table": "3",
    "guest": "Dany Stueland"
  },
  {
    "table": "3",
    "guest": "Guillaume Loinard-Gonzalez"
  },
  {
    "table": "3",
    "guest": "Lei Rivas Moron"
  },
  {
    "table": "3",
    "guest": "Lupita Mier Silva"
  },
  {
    "table": "3",
    "guest": "Melanie Barnaba"
  },
  {
    "table": "4",
    "guest": "Brian Mastenbrook"
  },
  {
    "table": "4",
    "guest": "Dr. Michael Delage Jr."
  },
  {
    "table": "4",
    "guest": "Emily Wollan"
  },
  {
    "table": "4",
    "guest": "Mr. Paul Mikowski"
  },
  {
    "table": "4",
    "guest": "Mr. Silas Talley"
  },
  {
    "table": "4",
    "guest": "Mrs. Alex Mikowski"
  },
  {
    "table": "4",
    "guest": "Mrs. Jess Talley"
  },
  {
    "table": "4",
    "guest": "Timothy Vanhala"
  },
  {
    "table": "5",
    "guest": "Cory Tripathy"
  },
  {
    "table": "5",
    "guest": "Dave Perczak"
  },
  {
    "table": "5",
    "guest": "Erica Kanzinger"
  },
  {
    "table": "5",
    "guest": "Tori Darnell"
  },
  {
    "table": "6",
    "guest": "Andrew Davis"
  },
  {
    "table": "6",
    "guest": "Cameron Dunbar"
  },
  {
    "table": "6",
    "guest": "Chloe Frey"
  },
  {
    "table": "6",
    "guest": "Colby Chase"
  },
  {
    "table": "6",
    "guest": "Katherine Jones"
  },
  {
    "table": "6",
    "guest": "Rae Powers"
  },
  {
    "table": "6",
    "guest": "Rashke Bradley"
  },
  {
    "table": "7",
    "guest": "Elias Diaz Escalona"
  },
  {
    "table": "7",
    "guest": "Gina (Patricia Eugenia) Lopezlira"
  },
  {
    "table": "7",
    "guest": "Kitty Lopezlira"
  },
  {
    "table": "7",
    "guest": "Lucy Gonz\u00e1lez Le\u00f3n"
  },
  {
    "table": "7",
    "guest": "Ms. Mar\u00eda Josefa Gonz\u00e1lez Marina"
  },
  {
    "table": "7",
    "guest": "Nuria Castells"
  },
  {
    "table": "7",
    "guest": "Ricardo Garc\u00eda Berumen Segura"
  },
  {
    "table": "8",
    "guest": "David Gilwan"
  },
  {
    "table": "8",
    "guest": "Geeta Rastogi"
  },
  {
    "table": "8",
    "guest": "Mohan Kolla"
  },
  {
    "table": "8",
    "guest": "Nishant Mishra"
  },
  {
    "table": "8",
    "guest": "Soha Kazmi"
  },
  {
    "table": "8",
    "guest": "Veronica Gilwan"
  },
  {
    "table": "9",
    "guest": "Ben Laubach"
  },
  {
    "table": "9",
    "guest": "Erin Nichols"
  },
  {
    "table": "9",
    "guest": "Kyle Franson"
  },
  {
    "table": "9",
    "guest": "Lexi Howard"
  },
  {
    "table": "9",
    "guest": "Madeleine Russell"
  },
  {
    "table": "9",
    "guest": "Maisey Schuler"
  },
  {
    "table": "9",
    "guest": "Rachel Zhang"
  },
  {
    "table": "9",
    "guest": "Samuel Lehn"
  },
  {
    "table": "10",
    "guest": "Della Keahna Warrior"
  },
  {
    "table": "10",
    "guest": "Grant"
  },
  {
    "table": "10",
    "guest": "Jack Ramey"
  },
  {
    "table": "10",
    "guest": "Jonah"
  },
  {
    "table": "10",
    "guest": "Philip Danziger"
  },
  {
    "table": "10",
    "guest": "Shannon Firooz"
  },
  {
    "table": "10",
    "guest": "Susan Lin"
  },
  {
    "table": "11",
    "guest": "Angie Perez"
  },
  {
    "table": "11",
    "guest": "Ashley Wilson"
  },
  {
    "table": "11",
    "guest": "Chloe Tyler"
  },
  {
    "table": "11",
    "guest": "Ela Pananon"
  },
  {
    "table": "11",
    "guest": "Jeremiah Harmon"
  }
];
